server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users   
    username: postgres
    password: 123456789   
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
 


jwt:
  secret: ${KEYSECRET_SECURITY:defaultSecret}
  expiration: ${EXPIRE_DAYS_SECURITY:3600000}

management:
  endpoints:
    web:
      exposure:
        include: "*"
