server:
  port: 8080
  
spring:
  datasource:
<<<<<<< HEAD
    url: jdbc:postgresql://localhost:5432/users   
    username: postgres
    password: 123456789   
=======
    url: jdbc:postgresql://localhost:5432/usuarios
    username: postgres
    password: 123456789
>>>>>>> 1c3f0d3 (Resuelto conflicto)
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
 

<<<<<<< HEAD

jwt:
  secret: ${KEYSECRET_SECURITY:defaultSecret}
  expiration: ${EXPIRE_DAYS_SECURITY:3600000}

=======
>>>>>>> 1c3f0d3 (Resuelto conflicto)
management:
  endpoints:
    web:
      exposure:
        include: "*"
